---
title: "Road to Kyiv"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library("tidyverse")
library("sf")
library("tmap")
library("units")
theme_set(ggthemes::theme_few())
```


```{r}
tmap_mode("view")

dist = units::as_units(100, "km")
max_dist = units::as_units(2420, "km")

progress_pc = dist/max_dist

locs = tribble(
 ~name, ~lat, ~lon,
   "Lon", 51.49796,-0.13298, 
  "Kyiv"  , 50.4488, 30.5237) %>% 
  st_as_sf(coords = c("lon", "lat"), crs="EPSG:4326")  

kyiv = tribble(
   ~lat, ~lon,
  #"london", 51.49796,-0.13298) %>% 
  50.4488, 30.5237) %>% 
  st_as_sf(coords = c("lon", "lat"), crs="EPSG:4326") %>% 
  st_transform("EPSG:27700") 

route = st_union(locs[,1]) %>% 
    st_cast("LINESTRING")

map_max = st_length(route)
map_dist = progress_pc * map_max


st_intersection(st_buffer(locs[1,], map_dist),
                route) %>% 
  mutate(name = "Progress") %>% 
  tm_shape() + tm_dots() 
```


```{r}
tibble(progress = drop_units(progress_pc)) %>% 
  ggplot(aes(y="progress", x=progress)) + geom_col() + 
  expand_limits(x=c(0,1)) +
  scale_x_continuous(labels=scales::percent)

```

